[tool.mypy]
exclude = ".venv/"
namespace_packages = true
explicit_package_bases = true

[tool.black]
line-length = 79

[tool.isort]
line_length = 79
profile = "black"

[tool.flake8]
exclude = [
    "venv",
    ".venv",
    "__pycache__",
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".vscode",
]
max-line-length = 79
